### ISSUE TITLE
switch case indentation

### ISSUE THREAD

**Issue by tnguyen14** [JedWatson/happiness#11]
It seems that `standard` enable switch case indentation with `"indent": [2, 2, { "SwitchCase": 1 }]`, but `happiness` does not have that enabled (just `"indent": [2, "tab"]`). Should switchcase indentation be enabled to be more consistent?

**Comment by wesleytodd** [comment]
Looks like we need to update the version of `eslint-config-standard` we are using.  If you want to submit a PR for that go ahead, or let me know and I will do it asap.

**Comment by tnguyen14** [comment]
@wesleytodd sorry for the late response. I'd love to make the contribution. I'm still very new to happiness and eslint, so any guidance/ advice is really appreciated.

I created #12 to update the version of `eslint-config-standard` as you suggested.

**Comment by wesleytodd** [comment]
PR looks good once we fix the tests, Ill close this out.  Thanks!

**Comment by tnguyen14** [comment]
@wesleytodd do you know if a new release would be created soon to make the changes from #13 available?

**Comment by wesleytodd** [comment]
@JedWatson & @dcousens got time for this?

**Comment by dcousens** [comment]
I haven't at the moment.   @wesleytodd if you haven't got time to publish a release I'll see if I can push it out over the weekend.

**Comment by wesleytodd** [comment]
Oh, I totally forgot you added me to npm :)  I can publish it for sure, just thought I couldn't.  I will do it within the next few hours.

**Comment by wesleytodd** [comment]
Published! https://www.npmjs.com/package/happiness
