### ISSUE TITLE
Add me to npm eslint-config-happiness

### ISSUE THREAD

**Issue by wesleytodd** [JedWatson/happiness#18]
@dcousens @JedWatson

Hey, Im trying to update to the newest standard stuff and it now requires an updated package for `eslint-config-happiness`.  Can one of you add me to that project on npm so I can publish my updates? The updates are here: https://github.com/wesleytodd/eslint-config-happiness

https://www.npmjs.com/package/eslint-config-happiness

Thanks!!

Side note: I published this one as well https://github.com/wesleytodd/eslint-config-happiness-jsx

**Comment by wesleytodd** [comment]
Ping :)

**Comment by JedWatson** [comment]
Sorry about the delay! Just added you.

**Comment by wesleytodd** [comment]
Thanks!! And no worries about the delay, one of my team members just ran into an error in the linting so I wanted to see if it was just a matter of updating or actually fixing something.  Turns out it was just updating.

**Comment by wesleytodd** [comment]
Oh, and where did the code go?  I can just publish from my repo for now, but if you want to take it back just let me know.
