### ISSUE TITLE
Consistency?

### ISSUE THREAD

**Issue by FlorianWendelborn** [JedWatson/happiness#2]
As far as I understand happiness is a standard which uses semicolons and tabs. Why doesn't the project itself use semicolons and tabs?

**Comment by dcousens** [comment]
@dodekeract right now,  I use https://github.com/feross/standard by default,  and the repository is checked using that.
We could probably have the repository check it self,  but that wasn't a priority initially.

**Comment by wesleytodd** [comment]
This is fixed in the new version.
