### ISSUE TITLE
--fix support for:  Split initialized 'var'/'const' declarations into multiple statements.

### ISSUE THREAD

**Issue by flesler** [JedWatson/happiness#24]
Hi,

This is one error (actually 2) that --fix won't fix. It seems like something that could be fixed just like the other things.

Thanks

**Comment by dcousens** [comment]
Hi @flesler,  you're probably better submitting this to https://github.com/feross/standard rather than here,  as this issue doesn't related specifically to rules that `happiness` changes from that module.
