### ISSUE TITLE
Snazzy

### ISSUE THREAD

**Issue by mathiasrw** [JedWatson/happiness#25]
Would be so awesome to get a flag so that the output gets snazzy - like https://github.com/feross/snazzy

(or even better, change default output and have a flag to get the traditional output)

**Comment by wesleytodd** [comment]
This is strictly a fork of standard with a few small changes.  So adding features that happiness does not have is not really the idea.

Seems like piping happiness to snazzy like they show in the example is the best route.  Or if you want, you can fork snazzy and swap out the underlying stuff for happiness.  

Maybe call it `hazzy` ;)
