### ISSUE TITLE
is happiness alive?

### ISSUE THREAD

**Issue by OlehDutchenko** [JedWatson/happiness#27]
@JedWatson hello!

is this project maintained? last activity was almost year ago (((

it is very unfortunate if the project was abandoned.

if you do not have the opportunity or time to further support the project, I would like to make a fork to develop the project further, with your permission.

**Comment by wesleytodd** [comment]
Hey @dutchenkoOleg!  I was the last person to manage the releases, and yes, I have not been great about it lately.  The process of doing an update should be fairly straight forward, the only reason I haven't is because I have not needed any of the new features from standard.  Is there something in particular that you want from standard that 7.x does not have?  If so I can look at updating to 10 this week.  Let me know!

**Comment by OlehDutchenko** [comment]
Hi! It would be great!
I will write to you, within a few days

**Comment by OlehDutchenko** [comment]
Hi!

At first I wanted to try to write important updates in parts, but eventually I came to the conclusion that they are all important in the aggregate - addintional new rules / relaxing some old rules / support for the new es6-7 syntax / update of the "eslint" version / improvement of the `--fix` command. That were debugged and tested by community and developers of standard.

Since over the past year there have been many changes and innovations in JavaScript development - it seems to me that ideal variant is to update completely `happiness` to full compatibility with the standard 10.

If this update becomes a problem for the `happiness` community and their projects supporting, it may be worthwhile to make a new release on the github with manual installation by absolute url (like `npm i gulpjs/gulp#4.0`) or to publish a separate package on npm

**Comment by wesleytodd** [comment]
Ok, sounds like it is worth doing for sure.  Let me take a look at this week.  I will update here when it is published.

**Comment by OlehDutchenko** [comment]
Is there some progress?

**Comment by wesleytodd** [comment]
Sorry about the delay, published 10.0.2 just now!

https://www.npmjs.com/package/happiness
