### ISSUE TITLE
remove not true "coming soon"

### ISSUE THREAD

**Issue by matkoniecz** [JedWatson/happiness#30]
https://github.com/JedWatson/happiness#text-editor-plugins

Converted from  #29 as project is dead and I am reviewing my PR list.

**Comment by wesleytodd** [comment]
https://github.com/JedWatson/happiness/commit/f19759f8949761b59900964bd8c879d5bfd07a58

Lol, not sure this is maintained anymore, and I am not going to push a commit or merge a PR to just to remove incorrect readme content.

**Comment by wesleytodd** [comment]
I actually think I remember writing that line and laughing to myself thinking "I hope someone writes this so I can use it". good times.
